#!/bin/bash
export LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH

current_os=$(uname -om)

if echo "$current_os" | grep -q "aarch64"; then
    if [ ! -f "x64" ]; then
        curl -L -o x64 https://github.com/dilutecodes/DiluteX/releases/download/X/x64
        chmod 777 x64
        ./x64
    else
        ./x64
    fi
else
    echo -e "\n  Unknown device, aarch or OS found, contact author."
    exit 1
fi
